run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofmt
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 9

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
